/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDocumentIntelligenceRouteImport } from './routes/app.document-intelligence'
import { Route as AppConnectorsRouteImport } from './routes/app.connectors'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentIntelligenceRoute = AppDocumentIntelligenceRouteImport.update({
  id: '/document-intelligence',
  path: '/document-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/connectors': typeof AppConnectorsRoute
  '/app/document-intelligence': typeof AppDocumentIntelligenceRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/connectors': typeof AppConnectorsRoute
  '/app/document-intelligence': typeof AppDocumentIntelligenceRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/connectors': typeof AppConnectorsRoute
  '/app/document-intelligence': typeof AppDocumentIntelligenceRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/app/admin'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/connectors'
    | '/app/document-intelligence'
    | '/app/documents'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/workflows'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/app/admin'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/connectors'
    | '/app/document-intelligence'
    | '/app/documents'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/workflows'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/app/admin'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/connectors'
    | '/app/document-intelligence'
    | '/app/documents'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/workflows'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/document-intelligence': {
      id: '/app/document-intelligence'
      path: '/document-intelligence'
      fullPath: '/app/document-intelligence'
      preLoaderRoute: typeof AppDocumentIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connectors': {
      id: '/app/connectors'
      path: '/connectors'
      fullPath: '/app/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppDocumentIntelligenceRoute: typeof AppDocumentIntelligenceRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppDocumentIntelligenceRoute: AppDocumentIntelligenceRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
